# frozen_string_literal: true
brew 'mas'                                                # CLI for the Mac App Store
brew 'asdf'
brew 'autojump'                                           # Make it easier to jump between directories
brew 'ctags'
brew 'dash'
brew 'ffmpeg'
brew 'graphicsmagick'
brew 'htop'                                               # Process manager
brew 'imagemagick'
brew 'openssl'
brew 'libxml2'
brew 'neovim', args: ['HEAD']                             # Prefered text editor
brew 'p7zip'
brew 'reattach-to-user-namespace'
brew 'the_silver_searcher'
brew 'tmux'
brew 'fzf'
brew 'yarn'                                               # Frontend package manager
brew 'bat'                                                # Replace for cat
brew 'ripgrep'                                            # Better search
brew 'lsd'                                                # Replace for ls
brew 'vifm'                                               # Prefered filemanager
brew 'moreutils'                                          # Usefull utils
brew 'jq'                                                 # CLI JSON processor
brew 'tidy-html5'                                         # HTML tool
brew 'stow'

# DB
cask 'phinze/cask/dbeaver-community'

# Zsh
brew 'zsh'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'

# Git client
brew 'gh'                                                 # CLI tool for GitHub
brew 'git'                                                # VCM
brew 'hub'                                                # I use hub browse
brew 'git-delta'                                          # Diff tool for CLI

cask 'alfred'
cask 'suspicious-package'                                 # Inspecting Mac installer package
cask 'vlc'                                                # Best video player
cask 'webpquicklook'                                      # Quicklook for Webp files
cask 'wkhtmltopdf'                                        # Html to PDF converter
cask 'macdown'                                            # Cool Markdown Editor
cask 'hiddenbar'                                          # Hide icons in menubar
cask 'docker'
cask 'google-chrome'
cask 'telegram'
cask 'iterm2'
cask 'kitty'
cask 'alacritty'
cask 'xquartz'
cask 'aldente'

# Fonts
cask 'font-fira-code'
cask 'font-jetbrains-mono'
cask 'font-jetbrains-mono-nerd-font'
cask 'font-ibm-plex'
cask 'font-blex-mono-nerd-font'

# Quicklook plugins https://github.com/sindresorhus/quick-look-plugins
cask 'qlcolorcode'                                        # Syntax highlighting for source code in quicklook
cask 'qlimagesize'                                        # Display the dimensions, DPI and file size
cask 'qlmarkdown'                                         # Quicklook markdown files
cask 'qlstephen'                                          # Quicklook plain text files without file extension
cask 'quicklook-csv'                                      # Quicklook CSM files
cask 'quicklook-json'                                     # Quicklook JSON files
