return {}
-- return {
--   "lukas-reineke/indent-blankline.nvim",
--   main = 'ibl',
--   config = function()
--     vim.opt.list = true
--     vim.opt.listchars:append "trail:⋅"
--     vim.opt.listchars:append "eol:↴"
--
--     vim.g.indent_blankline_filetype = {
--       "go",
--       "ruby",
--       "json",
--       "yaml",
--       "proto",
--       "bash",
--       "lua",
--     }
--     require("ibl").setup {
--       -- space_char_blankline = " ",
--       -- show_trailing_blankline_indent = false,
--       -- show_first_indent_level = false,
--       -- show_current_context = true,
--       -- show_current_context_start = false,
--     }
--   end
-- }
