alias cp="cp -iv"
alias rm="rm -iv"
alias mv="mv -iv"
alias ls="ls -FGh"
alias ll="ls -laFGh"
alias dotfiles="cd ~/.dotfiles"
alias dt="dotfiles"
alias sed="sed -E"
alias -g G="| grep "
alias server="python -m SimpleHTTPServer 8000"
alias tmux="tmux -2"
alias tns="tmux new-session -s"
alias tat="tmux attach-session -t"
alias v="vim"
alias reload!="source ~/.zshrc"
alias be="bundle exec"
alias lc='colorls -r'
alias rspec="clear; rspec"
alias dm="docker-machine"
alias mntnb="sshfs dev:/home/arty/projects/nb ~/mount/nb -ovolname=NB"
alias mntcp="sshfs dev:/home/arty/projects/cp ~/mount/cp -ovolname=CP"

