alias cp="cp -iv"
alias rm="rm -iv"
alias mv="mv -iv"
alias ls="ls -FGh"
alias ll="ls -laFGh"
alias dotfiles="cd ~/.dotfiles"
alias dt="dotfiles"
alias sed="sed -E"
alias -g G="| grep "
alias server="python -m SimpleHTTPServer 8000"
alias tmux="tmux -2"
alias vim="nvim"
alias v="vim"
alias reload!="source ~/.zshrc"
alias dm="docker-machine"

alias be="bundle exec"
alias rspec="clear; rspec"
alias fs="foreman start"
alias rr="rake routes"
alias rrg="rake routes G"

