AllCops:
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'

Metrics/LineLength:
  Max: 110

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "**/*_shared_examples.rb"

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true
