set linespace=5
set guifont=Menlo:h15  " if have space in font name use 'Courier\ New'

set guioptions-=m  "remove menu bar
set guioptions-=T  "remove toolbar
set guioptions-=r  "remove right-hand scroll bar
set guioptions-=L  "remove left-hand scroll bar
set lines=45 columns=200
set background=light
colorscheme sexy-railscasts-256
let g:airline_theme='base16_railscasts'

augroup VimScript
  autocmd!
  autocmd BufWritePost $MYGVIMRC source $MYGVIMRC | AirlineRefresh
augroup END
