set linespace=5
" set guifont=FuraCode\ Nerd\ Font\ Mono:h15
" set guifont=Operator\ Mono\ Book\ Nerd\ Font\ Complete:h15
set guifont=Iosevka\ Slab\ Light:h14

set guioptions-=m  "remove menu bar
set guioptions-=T  "remove toolbar
set guioptions-=r  "remove right-hand scroll bar
set guioptions-=L  "remove left-hand scroll bar
set lines=45 columns=200

augroup VimScript
  autocmd!
  autocmd BufWritePost $MYGVIMRC source $MYGVIMRC
augroup END

hi Comment gui=italic cterm=italic
hi htmlArg gui=italic cterm=italic
