set linespace=5
" set guifont=FuraCode\ Nerd\ Font\ Mono:h15
set guifont=Operator\ Mono\ Book\ Nerd\ Font\ Complete:h15

set guioptions-=m  "remove menu bar
set guioptions-=T  "remove toolbar
set guioptions-=r  "remove right-hand scroll bar
set guioptions-=L  "remove left-hand scroll bar
set lines=45 columns=200
set background=light

set background=dark
colorscheme two-firewatch
let g:airline_theme='twofirewatch'

augroup VimScript
  autocmd!
  autocmd BufWritePost $MYGVIMRC source $MYGVIMRC | AirlineRefresh
augroup END

hi Comment gui=italic cterm=italic
hi htmlArg gui=italic cterm=italic
