export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/Cellar

# Add my custom commands
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="/usr/local/opt/postgresql@11/bin/:$PATH"
export PATH="$HOME/go/bin:$PATH"
export PATH="${PATH}:${HOME}/Library/Python/3.7/bin"

export TMUX_PLUGIN_MANAGER_PATH="$HOME/.tmux/plugins"
export BAT_CONFIG_PATH="$HOME/.dotfiles/os/bat/bat.conf"

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Hide docker legacy commands on `docker help`
export DOCKER_HIDE_LEGACY_COMMANDS=true

export DOCKER_CLIENT_TIMEOUT=120
export COMPOSE_HTTP_TIMEOUT=120
