export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/Cellar

export PATH="/usr/local/Cellar/python3/3.6.3/bin:${PATH}"
export PATH="/usr/local/Cellar/python/2.7.14/bin:${PATH}"

# Add my custom commands
export PATH="$HOME/bin:$PATH"
