# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source ~/.zplug/init.zsh
setopt combiningchars
setopt no_global_rcs

zplug 'mafredri/zsh-async', from:'github', use:'async.zsh'
zplug 'zsh-users/zsh-autosuggestions', defer:3
zplug 'zsh-users/zsh-syntax-highlighting', defer:3
zplug "plugins/osx", from:oh-my-zsh
zplug 'zsh-users/zsh-completions', defer:3
zplug 'wfxr/forgit'

autoload -U compinit && compinit

for zsh_source in $HOME/.zsh/configs/*.zsh; do
  source $zsh_source
done

if ! zplug check --verbose; then
printf "Install? [y/N]: "
if read -q; then
    echo; zplug install
fi
fi

zplug load

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.zshrc.local ] && source ~/.zshrc.local

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

source /Users/artyomanikin/Library/Preferences/org.dystroy.broot/launcher/bash/br

# Base16 Shell
BASE16_SHELL="$HOME/.dotfiles/os/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"
